package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// emailServiceConfig captures the user-facing settings for the bundled
// docker-mailserver. It maps onto two postfix files: a transport map and a
// sender-access map.
type emailServiceConfig struct {
	Enabled         bool
	Hostname        string
	AgentDomain     string
	LimitDelivery   bool
	DeliveryDomains []string // domains agents may send to (besides the agent domain)
	LimitAccept     bool
	AcceptDomains   []string // domains/emails agents may receive from (besides the agent domain)
}

// dmsConfigDir returns the abs path to services/dms/config under root.
func dmsConfigDir(root string) string {
	return filepath.Join(root, "services", "dms", "config")
}

// loadEmailServiceConfig best-effort reads the current postfix-transport.cf
// and postfix-sender-access.cf to populate a config. If neither exists,
// returns a zero-value struct (Enabled=false).
func loadEmailServiceConfig(root string) *emailServiceConfig {
	c := &emailServiceConfig{}
	dir := dmsConfigDir(root)
	tPath := filepath.Join(dir, "postfix-transport.cf")
	sPath := filepath.Join(dir, "postfix-sender-access.cf")

	if data, err := os.ReadFile(tPath); err == nil {
		c.Enabled = true
		c.parseTransport(string(data))
	}
	if data, err := os.ReadFile(sPath); err == nil {
		c.Enabled = true
		c.parseSenderAccess(string(data))
	}
	return c
}

func (c *emailServiceConfig) parseTransport(s string) {
	c.LimitDelivery = false
	c.DeliveryDomains = nil
	hasCatchAll := false
	starSmtp := false
	for _, raw := range strings.Split(s, "\n") {
		line := strings.TrimSpace(raw)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		fields := strings.Fields(line)
		if len(fields) < 2 {
			continue
		}
		key := fields[0]
		dest := fields[1]
		switch {
		case strings.HasPrefix(dest, "lmtp:"):
			c.AgentDomain = key
		case key == "*" && strings.HasPrefix(dest, "error:"):
			hasCatchAll = true
		case key == "*" && strings.HasPrefix(dest, "smtp:"):
			starSmtp = true
		case strings.HasPrefix(dest, "smtp:"):
			c.DeliveryDomains = append(c.DeliveryDomains, key)
		}
	}
	c.LimitDelivery = hasCatchAll && !starSmtp
	if !c.LimitDelivery {
		c.DeliveryDomains = nil
	}
}

func (c *emailServiceConfig) parseSenderAccess(s string) {
	c.LimitAccept = false
	c.AcceptDomains = nil
	hasDot := false
	for _, raw := range strings.Split(s, "\n") {
		line := strings.TrimSpace(raw)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		fields := strings.Fields(line)
		if len(fields) < 2 {
			continue
		}
		key := fields[0]
		val := fields[1]
		if val != "OK" {
			continue
		}
		if key == "." {
			hasDot = true
			continue
		}
		if c.AgentDomain == "" {
			c.AgentDomain = key
			continue
		}
		if key == c.AgentDomain {
			continue
		}
		c.AcceptDomains = append(c.AcceptDomains, key)
	}
	c.LimitAccept = !hasDot
	if !c.LimitAccept {
		c.AcceptDomains = nil
	}
}

// SaveEmailService rewrites the two postfix files based on c. The
// `*-example.cf` siblings are used as scaffolding only when generating
// fresh — we generate canonical contents directly, which is simpler than
// patching the example file.
func (c *emailServiceConfig) Save(root string) error {
	if c.AgentDomain == "" {
		return fmt.Errorf("agent email domain is required")
	}
	dir := dmsConfigDir(root)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("creating %s: %w", dir, err)
	}
	transport := c.renderTransport()
	if err := os.WriteFile(filepath.Join(dir, "postfix-transport.cf"), []byte(transport), 0o644); err != nil {
		return err
	}
	sender := c.renderSenderAccess()
	if err := os.WriteFile(filepath.Join(dir, "postfix-sender-access.cf"), []byte(sender), 0o644); err != nil {
		return err
	}
	return nil
}

func (c *emailServiceConfig) renderTransport() string {
	var b strings.Builder
	b.WriteString("# RESTRICT SENDING TO EXTERNAL DOMAINS\n")
	b.WriteString("# Generated by Agent Configurator. Edit via the dashboard or by hand.\n\n")
	b.WriteString("# Own domain - deliver locally\n")
	fmt.Fprintf(&b, "%s    lmtp:unix:/var/run/dovecot/lmtp\n\n", c.AgentDomain)

	if c.LimitDelivery {
		b.WriteString("# Allowed external domains\n")
		for _, d := range c.DeliveryDomains {
			d = strings.TrimSpace(d)
			if d == "" || strings.EqualFold(d, c.AgentDomain) {
				// Agent's own domain is already routed via lmtp above —
				// repeating it as an smtp destination would be a no-op.
				continue
			}
			fmt.Fprintf(&b, "%s     smtp:\n", d)
		}
		b.WriteString("\n# Reject everything else\n")
		b.WriteString("*              error:5.7.1 Sending to this domain is not permitted\n")
	} else {
		b.WriteString("# Allowed external domains\n")
		b.WriteString("*\tsmtp:\n")
	}
	return b.String()
}

func (c *emailServiceConfig) renderSenderAccess() string {
	var b strings.Builder
	b.WriteString("# RESTRICT RECEIVING\n")
	b.WriteString("# Generated by Agent Configurator. Edit via the dashboard or by hand.\n\n")
	b.WriteString("# Agent domain - always allowed\n")
	fmt.Fprintf(&b, "%s    OK\n", c.AgentDomain)

	if c.LimitAccept {
		b.WriteString("\n# Allowed external sender domains\n")
		for _, d := range c.AcceptDomains {
			d = strings.TrimSpace(d)
			if d == "" || strings.EqualFold(d, c.AgentDomain) {
				// Agent's own domain is already accepted above.
				continue
			}
			fmt.Fprintf(&b, "%s          OK\n", d)
		}
	} else {
		b.WriteString("\n# Allow all external sender domains\n")
		b.WriteString(".          OK\n")
	}
	return b.String()
}

// splitCSV splits on commas, trims whitespace, drops empties.
func splitCSV(s string) []string {
	if strings.TrimSpace(s) == "" {
		return nil
	}
	parts := strings.Split(s, ",")
	out := make([]string, 0, len(parts))
	for _, p := range parts {
		p = strings.TrimSpace(p)
		if p != "" {
			out = append(out, p)
		}
	}
	return out
}

// joinCSV is the inverse for display in form fields.
func joinCSV(ss []string) string {
	return strings.Join(ss, ", ")
}

// hostnameDomain returns the parent domain of a hostname (everything past
// the first dot), or "" for bare hostnames.
func hostnameDomain(hostname string) string {
	hostname = strings.TrimSpace(hostname)
	if hostname == "" {
		return ""
	}
	if i := strings.Index(hostname, "."); i > 0 && i < len(hostname)-1 {
		return hostname[i+1:]
	}
	return ""
}
